# Generated by Django 5.1.3 on 2024-11-12 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=256)),
                ('picture', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('poll_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=64)),
                ('is_active', models.BooleanField()),
                ('is_public', models.BooleanField()),
                ('created_on', models.DateField()),
                ('expires_on', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('option_id', models.AutoField(primary_key=True, serialize=False)),
                ('option_text', models.CharField(max_length=128)),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.option')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.poll')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('user_id1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends1', to='base.user')),
                ('user_id2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends2', to='base.user')),
            ],
            options={
                'unique_together': {('user_id1', 'user_id2')},
            },
        ),
    ]
